MvcProjeKamp/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKamp.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EFWriterDal());
        WriterValidator validationRules = new WriterValidator();
        HeadingManager hm = new HeadingManager(new EFHeadingDal());
        public ActionResult Index()
        {
            var writervalues = wm.GetList();
            return View(writervalues);
        }
        [HttpGet]
        public ActionResult WriterAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult WriterAdd(Writer p)
        {
            
            ValidationResult results=validationRules.Validate(p);
            if (results.IsValid)
            {
                wm.WriterAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach(var x in results.Errors)
                    ModelState.AddModelError(x.PropertyName,x.ErrorMessage);
            }
            return View();
        }
        [HttpGet]
        public ActionResult WriterEdit(int id)
        {
            var writervalue=wm.Get(id);
            return View(writervalue);
        }
        [HttpPost]
        public ActionResult WriterEdit(Writer p)
        {
            ValidationResult results = validationRules.Validate(p);
            if (results.IsValid)
            {
                wm.WriterUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var x in results.Errors)
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
            }
            return View();
        }
    }
}

MvcProjeKamp/Views/Writer/Index.cshtml
@using EntityLayer.Concrete
@model List<Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var x in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @x.WriterTitle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@x.WriterName @x.WriterSurName</b></h2>
                                            <p class="text-muted text-sm"><b>Hakkında: </b>@x.WriterAbout </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-mail-bulk"></i></span> Mail : @x.WriterMail</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="@x.WriterImage" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="#" class="btn btn-sm bg-teal">
                                            <i class="fas fa-comments">Yazarın Başlıkları</i>
                                        </a>
                                        <a href="~/Writer/WriterEdit/@x.WriterId" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Profili Düzenle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <!-- /.card-body -->
            <!-- /.card-footer -->
        </div>
        <!-- /.card -->

    </section>
</body>
</html>
<br />
<a href="/Writer/WriterAdd" class="btn btn-info">YENİ YAZAR EKLE</a>
<script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>

MvcProjeKamp/Views/Writer/WriterAdd.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
@using (Html.BeginForm("WriterAdd", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
        <br />
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br />
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        <br />
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPass, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPass)
        <br />
        <br />
        @Html.Label("Yazar Ünvan")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        <br />
        @Html.Label("Yazar Resim Link")
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        <br />
        <button class="btn btn-info" style="width:95px;">EKLE</button>
    </div>

    <script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>


}

MvcProjeKamp/Views/Writer/WriterEdit.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Düzenleme</h2>
<br />
@using (Html.BeginForm("WriterEdit", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Ad")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
        <br />
        <br />
        @Html.Label("Soyad")
        @Html.TextAreaFor(x => x.WriterSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br />
        <br />
        @Html.Label("Mail")
        @Html.TextAreaFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        <br />
        @Html.Label("Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        <br />
        @Html.Label("Ünvan")
        @Html.TextAreaFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        <br />
        @Html.Label("Resim URL Linki")
        @Html.TextAreaFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        <br />
        @Html.Label("Şifre")
        @Html.TextAreaFor(x => x.WriterPass, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPass)
        <br />
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>}