MvcProjeKamp/Controllers/UserPanelController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MvcProjeKamp.Controllers
{
   
    public class UserPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EFHeadingDal());
        CategoryManager cm = new CategoryManager(new EFCategoryDal());
        MessageManager mm = new MessageManager(new EFMessageDal());
        MessageValidator mv = new MessageValidator();
        WriterManager wm = new WriterManager(new EFWriterDal());
        WriterValidator validationRules = new WriterValidator();
        ContentManager com = new ContentManager(new EFContentDal());
        Context c = new Context();
        int id;
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult MyProfile(int id=0)
        {
           string p = (string)Session["WriterMail"];
            id = c.writers.Where(x => x.WriterMail == p).Select(y => y.WriterId).FirstOrDefault();
            var writerid = wm.Get(id);
            return View(writerid);
        }
        [HttpPost]
        public ActionResult MyProfile(Writer p)
        {
            ValidationResult results = validationRules.Validate(p);
            if (results.IsValid)
            {
                wm.WriterUpdate(p);
                return RedirectToAction("MyProfile");
            }
            else
            {
                foreach (var x in results.Errors)
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
            }
            return View();
        }
        /// <summary>
        /// BAŞLIK KISIMLARI(HEADİNG)
        /// </summary>
        public ActionResult MyHeading(string p,int sayfa=1)
        {
            p = (string)Session["WriterMail"];
            var idinfo=c.writers.Where(x=>x.WriterMail==p).Select(y=>y.WriterId).FirstOrDefault();
            var values = hm.GetList2(idinfo).ToPagedList(sayfa,10);
            return View(values);
        }
        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> category = (from x in cm.GetList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            ViewBag.ctg = category;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            string m = (string)Session["WriterMail"];
            var idinfo = c.writers.Where(x => x.WriterMail == m).Select(y => y.WriterId).FirstOrDefault();
            p.HeadDate = DateTime.Now.ToShortDateString();
            p.WriterId = idinfo;
            p.HeadStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }
        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> category = (from x in cm.GetList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            ViewBag.ctg = category;
            var headingvalues = hm.Get(id);
            return View(headingvalues);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingvalue = hm.Get(id);
            headingvalue.HeadStatus = false;
            hm.HeadingDelete(headingvalue);
            return RedirectToAction("MyHeading");
        }
        /// <summary>
        /// BAŞLIK KISIMLARI(HEADİNG)
        /// </summary>
        /////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>
        /// MESAJ KISIMLARI(MESSAGE)
        /// </summary>
        public ActionResult MyMessages()
        {
            string p = (string)Session["WriterMail"];
            var messagevalues = mm.GetListInbox(p);
            return View(messagevalues);
        }
        public ActionResult Sendbox()
        {
            string p = (string)Session["WriterMail"];
            var messagevalues2 = mm.GetListSendbox(p);
            return View(messagevalues2);
        }
        public PartialViewResult MessageListMenu()
        {
            return PartialView();
        }
        public ActionResult ReadMail(int id)
        {
            var contactvalues = mm.Get(id);
            return View(contactvalues);
        }
        public ActionResult SendReadMail(int id)
        {
            var contactvalues = mm.Get(id);
            return View(contactvalues);
        }
        [HttpGet]
        public ActionResult MessageAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MessageAdd(Message p)
        {
            string sender = (string)Session["WriterMail"];
            ValidationResult results = mv.Validate(p);
            if (results.IsValid)
            {
                p.MessageSenderMail = sender;
                p.MessageDate = DateTime.Parse(DateTime.Now.ToString());
                mm.MessageAdd(p);
                return RedirectToAction("Sendbox");
            }
            else
            {
                foreach (var x in results.Errors)
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
            }
            return View();
        }
        /// <summary>
        /// MESAJ KISIMLARI(MESSAGE)
        /// </summary>
        /////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>
        /// Yazı KISIMLARI(Content)
        /// </summary>
        public ActionResult MyContect(string p)
        {
            p=(string)Session["WriterMail"];
            var writerid = c.writers.Where(x => x.WriterMail == p).Select(y=>y.WriterId).FirstOrDefault();
            var contentvalues = com.GetListByWriter(writerid);
            return View(contentvalues);
        }
        [HttpGet]
        public ActionResult AddContect()
        {
            List<SelectListItem> heading = (from x in hm.GetList() select new SelectListItem { Text = x.HeadName, Value = x.HeadId.ToString() }).ToList();
            ViewBag.d = heading;
            return View();
        }
        [HttpPost]
        public ActionResult AddContect(Content p)
        {
            string mail = (string)Session["WriterMail"];
            var writeridinfo=c.writers.Where(x=>x.WriterMail==mail).Select(y=>y.WriterId).FirstOrDefault();
            p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterId= writeridinfo;
            com.ContentAdd(p);
            return RedirectToAction("MyContect");
        }
    }
}

MvcProjeKamp/Views/UserPanel/AddContect.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContect";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using (Html.BeginForm("AddContect", "UserPanel", FormMethod.Post))
{

     <div class="form-group">
         @Html.Label("Yazını Yazın")
         @Html.TextAreaFor(x => x.ContentValue, 4, 30, new { @class = "form-control" })
         @Html.ValidationMessageFor(x => x.ContentValue)
         <br />
         @Html.Label("Başlık Seçin")
         @Html.DropDownListFor(x => x.HeadId, (List<SelectListItem>)ViewBag.d, new { @class = "form-control" })
         @Html.ValidationMessageFor(x => x.HeadId)
    <br />
         <button class="btn btn-info">Kaydet</button>
     </div>}
<script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>

MvcProjeKamp/Views/UserPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using (Html.BeginForm("EditHeading", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x=>x.HeadDate)
        @Html.HiddenFor(x=>x.HeadId)
        @Html.HiddenFor(x=>x.WriterId)
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadName)
        <br />
        <br />
        @Html.Label("Kategori Seç")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.ctg, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>}
<script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>

MvcProjeKamp/Views/UserPanel/MessageAdd.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "MessageAdd";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "UserPanel")
                <!-- /.col -->
                <div class="col-md-9" style="margin-top:10px;">
                    @using (Html.BeginForm("MessageAdd", "UserPanel", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Yazar Mail")
                                    @Html.TextBoxFor(x => x.MessageReceiverMail, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.MessageReceiverMail)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Konu")
                                    @Html.TextBoxFor(x => x.MessageSubject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.MessageSubject)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesajınız")
                                    <textarea id="compose-textarea" name="MessageContent" class="form-control" style="height:auto;">

                    </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Yükle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>}
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
$(function () {
    //Add text editor
    $('#compose-textarea').summernote()
  })</script>
</body>
</html>

MvcProjeKamp/Views/UserPanel/MyMessages.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "MyMessages";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu","UserPanel")
            <!-- /.col -->
            <div class="col-md-9" style="margin-top:10px;">

                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Kişisel Gelen Kutu</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var x in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/UserPanel/ReadMail/@x.MessageID">@x.MessageSenderMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@x.MessageSubject</b>
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">Gönderilen Tarih : @(((DateTime)x.MessageDate).ToString("dd-MM-yyyy"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <script>
            $(function () {
                //Enable check and uncheck all functionality
                $('.checkbox-toggle').click(function () {
                    var clicks = $(this).data('clicks')
                    if (clicks) {
                        //Uncheck all checkboxes
                        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)
                        $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')
                    } else {
                        //Check all checkboxes
                        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)
                        $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')
                    }
                    $(this).data('clicks', !clicks)
                })

                //Handle starring for glyphicon and font awesome
                $('.mailbox-star').click(function (e) {
                    e.preventDefault()
                    //detect type
                    var $this = $(this).find('a > i')
                    var glyph = $this.hasClass('glyphicon')
                    var fa = $this.hasClass('fa')

                    //Switch states
                    if (glyph) {
                        $this.toggleClass('glyphicon-star')
                        $this.toggleClass('glyphicon-star-empty')
                    }

                    if (fa) {
                        $this.toggleClass('fa-star')
                        $this.toggleClass('fa-star-o')
                    }
                })
            })
        </script>
        <!-- /.row -->
    </section>
    <script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <link rel="stylesheet" href="/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

MvcProjeKamp/Views/UserPanel/MyProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "MyProfile";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@using (Html.BeginForm("MyProfile", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @*@Html.Label("ID")*@
        @Html.HiddenFor(x => x.WriterId, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Ad")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
        <br />
        <br />
        @Html.Label("Soyad")
        @Html.TextAreaFor(x => x.WriterSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br />
        <br />
        @Html.Label("Mail")
        @Html.TextAreaFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        <br />
        @Html.Label("Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        <br />
        @Html.Label("Ünvan")
        @Html.TextAreaFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        <br />
        @Html.Label("Resim URL Linki")
        @Html.TextAreaFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        <br />
        @Html.Label("Şifre")
        @Html.TextAreaFor(x => x.WriterPass, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPass)
        <br />
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>}

MvcProjeKamp/Views/UserPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using (Html.BeginForm("NewHeading", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadName)
        <br />
        <br />
        @Html.Label("Kategori Seç")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.ctg, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />
        <button class="btn btn-info">BAŞLIK &nbsp; OLUŞTUR</button>
    </div>}
<script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>

MvcProjeKamp/Views/UserPanel/ReadMail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "ReadMail";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu","UserPanel")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mail Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->

                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu:@Html.DisplayFor(x => x.MessageSubject)</h5>
                                <h6>
                                    Kimden:@Html.DisplayFor(x => x.MessageSenderMail)

                                    <span class="mailbox-read-time float-right" style="font-size:15px;">Gönderilen Tarih: @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString()</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>Mesaj;</p>
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>
                            </div>
                            <div class="mailbox-controls with-border text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Delete">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Reply">
                                        <i class="fas fa-reply"></i>
                                    </button>
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Forward">
                                        <i class="fas fa-share"></i>
                                    </button>
                                </div>
                                <!-- /.btn-group -->
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">
                                    <i class="fas fa-print"></i>
                                </button>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
    <script src="/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>